### ISSUE TITLE
Registration of [transfer-chain 0.0 application/json] failed

### ISSUE THREAD

**Issue by messbees** [delventhalz/transfer-chain-js#5]
```
$ npm start

> transfer-chain-processor@0.0.0 start /home/ubuntu/transfer-chain-js/processor
> node index.js

Initializing JSON handler for Transfer-Chain
Connected to tcp://localhost:4004
Registration of [transfer-chain 0.0 application/json] failed
```

validator and REST API are launched with default network settings. how to solve?

**Comment by felison692** [comment]
Same issue,
¿any idea?

**Comment by delventhalz** [comment]
Not sure. Can you give me steps to reproduce? I followed the steps in the Readme and got a success:

```bash
git clone https://github.com/delventhalz/transfer-chain-js.git
cd transfer-chain-js/client/
npm install
npm run build
cd ../processor/
npm install
cd ../
docker-compose up
```

Then in a new Terminal:
```bash
cd processor/
npm start
```

That got me the following output:
```

> transfer-chain-processor@0.0.0 start /Users/a6003240/Documents/transfer-chain-js/processor
> node index.js

Initializing JSON handler for Transfer-Chain
Connected to tcp://localhost:4004
Registration of [transfer-chain 0.0 application/json] succeeded
```

**Comment by MattiaGo** [comment]
same issue for me, looping with:
Initializing JSON handler for Transfer-Chain

Connected to tcp://localhost:4004
Disconnected from tcp://localhost:4004
Attempting to reconnect to tcp://localhost:4004
Registration of [transfer-chain 0.0 application/json] Failed! ValidatorConnectionError: The connection to the validator was lost
    at /home/mattia/transfer-chain-js/processor/node_modules/sawtooth-sdk/messaging/stream.js:90:9
    at Array.forEach (<anonymous>)
    at Stream._handleDisconnect (/home/mattia/transfer-chain-js/processor/node_modules/sawtooth-sdk/messaging/stream.js:88:32)
    at exports.Socket.<anonymous> (/home/mattia/transfer-chain-js/processor/node_modules/sawtooth-sdk/messaging/stream.js:71:58)
    at exports.Socket.emit (events.js:314:20)
    at Object.self._zmq.onMonitorEvent (/home/mattia/transfer-chain-js/processor/node_modules/zeromq/lib/index.js:543:12)

It keep repeating this messages
